[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
authors = ["DaveDev42"]
license = "MIT OR Apache-2.0"
edition = "2021"
repository = "https://github.com/DaveDev42/tauri-plugin-mcp"
